### ISSUE TITLE
[YOUTUBEJS][Player]: Failed to extract n-token decipher algorithm

### ISSUE THREAD

**Issue by BhaveshBasrani** [retrouser955/discord-player-youtubei#15] opened 2024-07-24 12:08 UTC
![image](https://github.com/user-attachments/assets/ecddb271-05f3-49f2-aab6-e7689b0251e9)
Nodejs v20
Was working fine until 2 seconds ago

**Comment by retrouser955** [comment] 2024-07-24 15:02
Just restart your bot. It should fix it.

**Comment by Zythoxic** [comment] 2024-07-24 20:12
Having the same issue and restarted the bot multiple times. Also tried down- and upgrading the package, same issue in all versions.

Was working completely fine yesterday, today it's not working anymore and just giving the n-token error.

**Comment by retrouser955** [comment] 2024-07-25 01:52
AFAIK I can't do anything until youtubei.js fixes this as it's an internal error.

View: LuanRT/youtube.js#698

**Comment by retrouser955** [comment] 2024-07-25 05:17
@Zythoxic @BhaveshBasrani try using the ANDROID client in the useClient option
```ts
player.extractors.register(YoutubeiExtractor, {
   ...otherOptions,
   useClient: "ANDROID"
})
```
Ignore the error after doing this and see if streaming works as intended

**Comment by L-uu** [comment] 2024-07-25 08:51
> try using the ANDROID client in the useClient option

This didn't work for me sadly

**Comment by retrouser955** [comment] 2024-07-25 09:30
@L-uu This is actually my bad. It seems I'm lost in my own code also. The correct syntax is
```ts
player.extractors.register(YoutubeiExtractor, {
   ...otherOptions,
   streamOptions: {
      useClient: "ANDROID"
   } 
})
```

**Comment by L-uu** [comment] 2024-07-25 09:44
Tbf I should've probably figured that out myself too lmao, but while still displaying the same error it **does** play music.

**Comment by Zythoxic** [comment] 2024-07-25 11:57
Can confirm using the Android client it does play the music again, despite the error.

**Comment by BhaveshBasrani** [comment] 2024-07-25 16:52
Damm its actually a big issue
y does it occur tho?
shld i switch to spotify?

**Comment by BhaveshBasrani** [comment] 2024-07-25 16:54
![image](https://github.com/user-attachments/assets/828c22c5-e4c6-4cda-a54f-3a8b80811fc4)

**Comment by iTsMaaT** [comment] 2024-07-25 16:56
@BhaveshBasrani You cannot just switch to spotify, as it uses youtube to get the sound, or soundcloud if youtube is disabled

**Comment by BhaveshBasrani** [comment] 2024-07-25 16:59
Lavalink then ig

**Comment by iTsMaaT** [comment] 2024-07-25 17:00
adding the android client will still log this error, but the bot will work as intented so its not really an issue

**Comment by retrouser955** [comment] 2024-07-26 10:18
> Lavalink then ig

switching to lavalink is not a fix as they also need to scrape youtube for streaming.

**Comment by retrouser955** [comment] 2024-07-26 10:19
> ![image](https://private-user-images.githubusercontent.com/170641250/352223365-828c22c5-e4c6-4cda-a54f-3a8b80811fc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODkzOTksIm5iZiI6MTcyMTk4OTA5OSwicGF0aCI6Ii8xNzA2NDEyNTAvMzUyMjIzMzY1LTgyOGMyMmM1LWU0YzYtNGNkYS1hNTRmLTNhOGI4MDgxMWZjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQxMDE4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDAyZmUyMTlhN2ZmNWE1NGM3OGU3M2MxMGI0ZmZlOTcyNjJjOTkxNTUzM2VkMTYxMjI0MDE2NTNlODc5MGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S46hNQg-WrpN4UP_KpyEDMGYAjKtAtCmVbRAuRH244w)

ignore this. it should play music

**Comment by retrouser955** [comment] 2024-07-26 12:58
This issue is identified to be fixed in the latest version of `discord-player-youtubei`

**Comment by retrouser955** [comment] 2024-07-31 05:36
This is happening again as YouTube changed their validation.

**Comment by retrouser955** [comment] 2024-08-01 03:16
Identified the issue. Nothing I can do until youtubei.js released 10.3.0

**Comment by retrouser955** [comment] 2024-08-01 03:22
See LuanRT/YouTube.js#713

**Comment by retrouser955** [comment] 2024-08-01 09:27
`npm i discord-player-youtubei@latest`

**Closed by retrouser955** 2024-08-01 09:27 UTC
Labels: bug
